--- !com.dev.huining.soft.web.zfire.dto.configuration.ListConfiguration
  listConfigs:
# ---------------------------------------------------------
      - id: pagelist
        title: 页面组件列表
        function: function
        mainClass: class
        enableSelect: 1
        multiSelect: 1
        pk: ['id']
        pkType: ['s']

        headerOperations:
            - text: 添加
              style: add_page_style
              url: page=00000008
              frameType: 0
              function: function
              scriptFunction: addRow
              enableKey: {}
            - text: 删除
              style: style
              url: url
              frameType: 0
              function: function
              scriptFunction: deleteRows
              enableKey: {}
        rowOperations:
            - text: 删除
              style: style
              url: url
              frameType: 0
              function: UC_DELETE_PAGE
              scriptFunction: scriptFunction
              enableKey: {deleteflag: 1}
# ---------------------------------------------------------
      - id: uclist
        title: UC列表
        function: function
        mainClass: class
        enableSelect: 1
        multiSelect: 1
        pk: ['id']
        pkType: ['s']

        headerOperations:
            - text: 添加
              url: page=00000002
              frameType: 0
              function: function
              scriptFunction: addRow
              btnStyle: btn-success
              btnIcon: icon-plus
              enableKey: {}

        rowOperations:
            - text: 删除
              style: style
              url: url
              frameType: 0
              function: UC_DELETE_UCCFG
              scriptFunction: deleteRow
              btnStyle: btn-danger
              btnIcon: icon-trash
              enableKey: {deleteflag: 1}
# ---------------------------------------------------------
      - id: uccvscfglist
        title: UC属性字段列表
        function: function
        mainClass: class
        enableSelect: 1
        multiSelect: 1
        pk: ['id']
        pkType: ['s']

        headerOperations:
            - text: 添加
              url: page=00000010
              frameType: 0
              function: function
              scriptFunction: addCvscfgRow
              enableKey: {}

        rowOperations:
            - text: 删除
              style: style
              url: url
              frameType: 0
              function: UC_DELETE_CVSCFG
              scriptFunction: deleteRow
              enableKey: {deleteflag: 1}

# ---------------------------------------------------------
      - id: ucviewcfglist
        title: UC视图配置列表
        function: function
        mainClass: class
        enableSelect: 1
        multiSelect: 1
        pk: ['id']
        pkType: ['s']

        headerOperations:
            - text: 添加
              url: page=00000009
              frameType: 0
              function: function
              scriptFunction: addViewcfgRow
              enableKey: {}

        rowOperations:
            - text: 删除
              style: style
              url: url
              frameType: 0
              function: UC_DELETE_VIEWCFG
              scriptFunction: deleteRow
              enableKey: {deleteflag: 1}

# ---------------------------------------------------------
      - id: layoutlist
        title: 布局列表
        function: function
        mainClass: class
        enableSelect: 1
        multiSelect: 1
        pk: ['id']
        pkType: ['s']

        headerOperations:
            - text: 添加布局
              url: page=00000012
              frameType: 0
              function: function
              scriptFunction: addRow
              enableKey: {}
            - text: 添加类型
              url: page=00000013
              frameType: 0
              function: function
              scriptFunction: addRow
              enableKey: {}
            - text: 添加实例
              url: page=00000014
              frameType: 0
              function: function
              scriptFunction: addRow
              enableKey: {}

        rowOperations:
            - text: 删除
              style: style
              url: url
              frameType: 0
              function: UC_DELETE_UC
              scriptFunction: scriptFunction
              enableKey: {deleteflag: 1}
# ---------------------------------------------------------
      - id: orgzlist
        title: 组织机构列表
        function: function
        mainClass: class
        enableSelect: 1
        multiSelect: 1
        pk: ['id']
        pkType: ['s']

        headerOperations:
            - text: 删除
              url: page=00000012
              frameType: 0
              function: function
              scriptFunction: deleteRow
              btnStyle: btn-danger
              btnIcon: icon-trash
              enableKey: {}
            - text: 添加
              url: page=00000016
              frameType: 0
              function: function
              scriptFunction: addRow
              btnStyle: btn-success
              btnIcon: icon-plus
              enableKey: {}
