var tpCdCache={};
$.data(tpCdCache,"cdYorNTp",[{"name":"是","cdTp":"Y"},{"name":"否","cdTp":"N"}]);

var labelCache = {};
$.data(labelCache, "addPerson", [{"label":"证件类型","name":"idTpCd","s-list":"cdIdTp"},{"label":"证件号码","name":"idNum"},{"label":"证件有效期","name":"idExpiryDt"},{"label":"发证机关代码","name":"issueZoneTpCd","s-list":"cdZoneTp"},{"label":"境内外标志","name":"abroadTpCd","s-list":"cdAbroadTp"},{"label":"客户名称","name":"clientName"},{"label":"性别","name":"genderTpCd","s-list":"cdGenderTp"},{"label":"国籍","name":"countryTpCd","s-list":"cdCountryTp"},{"label":"出生日期","name":"birthDt"},{"label":"地址类型","name":"adrUsageTpCd","s-list":"cdAdrUsageTp"},{"label":"邮政编码","name":"postCode"},{"label":"具体地址","name":"address"},{"label":"联系方式","name":"ctcmthTpCd","s-list":"cdCtcmthTp"},{"label":"联系信息","name":"ctcmthNum"},{"label":"职业","name":"occupationTpCd","s-list":"cdOccupationTp"},{"label":"非居民标识","name":"residentTpCd","s-list":"cdResidentTp"}]);
$.data(labelCache, "updatePerson", [{"label":"客户号","name":"clientId"},{"label":"客户类型","name":"clientCode"},{"label":"客户名称","name":"clientName"},{"label":"客户状态","name":"clientStTpCd","s-list":"cdClientStTp"},{"label":"开拓人（员工编号）","name":"developEmpNo"},{"label":"常驻国家","name":"premCountryTpCd","s-list":"cdCountryTp"},{"label":"居民类型","name":"residentTpCd","s-list":"cdResidentTp"},{"label":"信息完整标识","name":"infoIntegFlag","s-list":"cdYorNTp"},{"label":"复核标识","name":"checkInd","s-list":"cdYorNTp"},{"label":"离岸客户标识","name":"offshoreInd","s-list":"cdYorNTp"},{"label":"开户机构","name":"createInst"},{"label":"开户柜员","name":"createTlr"},{"label":"开户时间","name":"createTms"},{"label":"所属客户经理","name":"customerManager"},{"label":"国籍","name":"countryTpCd","s-list":"cdCountryTp"},{"label":"籍贯","name":"zoneTpCd","s-list":"cdZoneTp"},{"label":"民族","name":"nationTpCd","s-list":"cdNationTp"},{"label":"出生日期","name":"birthDt"},{"label":"婚姻状况","name":"maritalTpCd","s-list":"cdMaritalTp"},{"label":"性别","name":"genderTpCd","s-list":"cdGenderTp"},{"label":"最高学历","name":"eduTpCd","s-list":"cdEduTp"},{"label":"最高学位","name":"degreeTpCd","s-list":"cdDegreeTp"},{"label":"客户称呼","name":"title"},{"label":"工作单位","name":"companyName"},{"label":"工作单位性质","name":"orgCharticTpCd","s-list":"cdOrgCharticTp"},{"label":"工作单位所属行业","name":"industryTpCd","s-list":"cdIndustryTp"},{"label":"工作部门","name":"department"},{"label":"员工编号","name":"empNo"},{"label":"营销机构号","name":"cmpnInst"},{"label":"职业","name":"occupationTpCd","s-list":"cdOccupationTp"},{"label":"职务","name":"positionTpCd","s-list":"cdPositionTp"},{"label":"职称","name":"titleTpCd","s-list":"cdTitleTp"},{"label":"本行员工标识","name":"bankEmpInd"},{"label":"户籍","name":"domicile"},{"label":"结婚纪念日","name":"maritalDt"},{"label":"住宅类型","name":"houseTpCd","s-list":"cdHouseTp"},{"label":"户籍所在地","name":"domicileLo"},{"label":"家庭人口","name":"familyPpn"},{"label":"供养人口","name":"supportPpn"},{"label":"子女数量","name":"childCount"},{"label":"客户标识","name":"clientFlag"},{"label":"存款人身份核实结果","name":"clientFlag"},{"label":"投资意愿","name":"investIntention"},{"label":"投资方向","name":"investDirection"},{"label":"毕业日期","name":"grdtDt"},{"label":"毕业学校","name":"grdtSchool"},{"label":"所学专业","name":"major"},{"label":"政治面貌","name":"politicalTpCd","s-list":"cdPoliticalTp"},{"label":"所属街道派出所","name":"policeStationLo"},{"label":"宗教信仰","name":"religionTpCd","s-list":"cdReligionTp"},{"label":"工作单位企业规模","name":"scaleTpCd","s-list":"cdScaleTp"},{"label":"最后更新的时间","name":"lastUpdateTms"}]);
$.data(labelCache, "updatePersonAddress",[{"name":"clientId","label":"客户号"},{"name":"adrUsageTpCd","label":"地址类型","s-list":"cdAdrUsageTp"},{"name":"address","label":"详细地址"},{"name":"adrOneCode","label":"省/直辖市"},{"name":"adrTwoCode","label":"市"},{"name":"adrThreeCode","label":"区/县"},{"name":"startTime","label":"联系时段（开始）"},{"name":"endTime","label":"联系时段（结束）"},{"name":"postCode","label":"邮政编码"}]);
$.data(labelCache, "addPersonAddress",[{"name":"clientId","label":"客户号"},{"name":"adrUsageTpCd","label":"地址类型","s-list":"cdAdrUsageTp"},{"name":"address","label":"详细地址"},{"name":"adrOneCode","label":"省/直辖市"},{"name":"adrTwoCode","label":"市"},{"name":"adrThreeCode","label":"区/县"},{"name":"startTime","label":"联系时段（开始）"},{"name":"endTime","label":"联系时段（结束）"},{"name":"postCode","label":"邮政编码"}]);
$.data(labelCache, "addPersonName",[{"name":"clientId","label":"客户号"},{"label":"名称类型","name":"nameUsageTpCd","s-list":"cdNameUsageTp"},{"label":"名称","name":"name"},{"label":"最后更新时间","name":"lastUpdateTms"}]);
$.data(labelCache, "updatePersonName",[{"name":"clientId","label":"客户号"},{"label":"名称类型","name":"nameUsageTpCd","s-list":"cdNameUsageTp"},{"label":"名称","name":"name"},{"label":"最后更新时间","name":"lastUpdateTms"}]);
$.data(labelCache, "addPersonIdentifier",[{"name":"clientId","label":"客户号"},{"label":"证件类型","name":"idTpCd","s-list":"cdIdTp"},{"label":"证件号码","name":"idNum"},{"label":"证件地址","name":"idAddress"},{"label":"证件有效期","name":"expiryDt"},{"label":"最后更新时间","name":"lastUpdateTms"}]);
$.data(labelCache, "updatePersonIdentifier",[{"name":"clientId","label":"客户号"},{"label":"证件类型","name":"idTpCd","s-list":"cdIdTp"},{"label":"证件号码","name":"idNum"},{"label":"证件地址","name":"idAddress"},{"label":"证件有效期","name":"expiryDt"},{"label":"最后更新时间","name":"lastUpdateTms"}]);
$.data(labelCache, "addPersonContactMethod",[{"name":"clientId","label":"客户号"},{"label":"联系类型","name":"ctcmthTpCd","s-list":"cdCtcmthTp"},{"label":"联系电话","name":"ctcmthNum"},{"label":"最后更新时间","name":"lastUpdateTms"}]);
$.data(labelCache, "updatePersonContactMethod",[{"name":"clientId","label":"客户号"},{"label":"联系类型","name":"ctcmthTpCd","s-list":"cdCtcmthTp"},{"label":"联系电话","name":"ctcmthNum"},{"label":"最后更新时间","name":"lastUpdateTms"}]);
$.data(labelCache, "addPersonRelatedPerson",[{"name":"clientId","label":"客户号"},{"label":"关联人类型","name":"relTpCd"},{"label":"关联人中文名","name":"chinesename"},{"label":"关联人证件类型","name":"idTpCd","s-list":"cdIdTp"},{"label":"关联人证件号码","name":"idNum"},{"label":"关联人手机号码","name":"mobile"},{"label":"最后更新时间","name":"lastUpdateTms"}]);
$.data(labelCache, "updatePersonRelatedPerson",[{"name":"clientId","label":"客户号"},{"label":"关联人类型","name":"relTpCd"},{"label":"关联人中文名","name":"chinesename"},{"label":"关联人证件类型","name":"idTpCd","s-list":"cdIdTp"},{"label":"关联人证件号码","name":"idNum"},{"label":"关联人手机号码","name":"mobile"},{"label":"最后更新时间","name":"lastUpdateTms"}]);
$.data(labelCache, "addPersonFinance",[{"name":"clientId","label":"客户号"},{"label":"货币类型","name":"currencyTpCd"},{"label":"资产负债类型","name":"balanceTpCd","s-list":"cdBalanceTp"},{"label":"金额","name":"balanceAmt"},{"label":"最后更新时间","name":"lastUpdateTms"}]);
$.data(labelCache, "addPersonClientRel",[{"name":"fromClientId","label":"客户编号"},{"name":"relTpCd","label":"关系类型","s-list":"cdRelTp"},{"name":"fromClientId","label":"主体关系客户号"},{"name":"toClientId","label":"从属关系客户号"}]);
$.data(labelCache, "updatePersonClientRel",[{"name":"fromClientId","label":"客户编号"},{"name":"relTpCd","label":"关系类型","s-list":"cdRelTp"},{"name":"fromClientId","label":"主体关系客户号"},{"name":"toClientId","label":"从属关系客户号"}]);

$.data(labelCache,"addOrg",[{"name":"clientCode","label":"企业客户类型"},{"name":"idNum","label":"证件号码*"},{"name":"expiryDt","label":"证件有效期*"},{"name":"establishedDt","label":"成立日期*"},{"name":"clientName","label":"客户名称*"},{"name":"idNum01","label":"法人证件号码*"},{"name":"chineseName01","label":"法人中文名*"},{"name":"chineseName02","label":"财务联系人中文名*"},{"name":"idNum02","label":"财务联系人证件号码*"},{"name":"mobile01","label":"法人手机号码*"},{"name":"mobile02","label":"财务联系人手机号码*"},{"name":"developEmpNo","label":"开拓人(员工编号)"},{"name":"registerDt","label":"注册登记日期*"},{"name":"postCode","label":"邮政编码"},{"name":"address","label":"具体地址*"},{"name":"ctcmthNum","label":"联系信息*"},{"name":"spvisorDepartment","label":"上级主管部门"},{"name":"loanCardNo","label":"贷款卡号"},{"name":"businessScope","label":"经营范围"},{"name":"staffNum","label":"员工人数"},{"name":"loyalScore","label":"忠诚度得分"},{"name":"defaultPb","label":"违约概率"},{"name":"taxregAcctNo","label":"税务登记银行账号"},{"name":"taxregAcctBankName","label":"税务登记银行"},{"name":"balanceTpCd","label":"资产负债类型"},{"name":"registerAmt","label":"注册资金*"},{"name":"idTpCd","label":"证件类型*"},{"name":"clientStTpCd","label":"客户分类"},{"name":"clientStTpCd","label":"客户状态"},{"name":"relTpCd01","label":"关联人类型"},{"name":"idTpCd01","label":"法人证件类型*"},{"name":"relTpCd02","label":"关联人类型"},{"name":"idTpCd02","label":"财务联系人证件类型*"},{"name":"langTpCd","label":"通讯语言"},{"name":"premCountryTpCd","label":"常驻国家"},{"name":"residentTpCd","label":"居民类型"},{"name":"offshoreInd","label":"离岸客户标识"},{"name":"orgTpCd","label":"企业类型*"},{"name":"industryTpCd","label":"行业类型*"},{"name":"economicTpCd","label":"经济类型*"},{"name":"rgstCountryTpCd","label":"注册国家*"},{"name":"rgstZoneTpCd","label":"注册地区*"},{"name":"ownershipTpCd","label":"企业性质*"},{"name":"listedTpCd","label":"上市类型"},{"name":"miitScaleTpCd","label":"企业规模*"},{"name":"adrUsageTpCd","label":"地址类型"},{"name":"regionTpCd","label":"所属地区"},{"name":"economicRegionTpCd","label":"所属经济区域"},{"name":"ctcmthTpCd","label":"联系类型*"},{"name":"spclEconomicTpCd","label":"特殊经济区代码"},{"name":"loanValidInd","label":"贷款卡有效标识"},{"name":"businessStTpCd","label":"经营状态"},{"name":"taxpayerTpCd","label":"纳税人类型"},{"name":"currencyTpCd","label":"货币类型*"}]);
$.data(labelCache,"updateOrg",[{"name":"clientCode","label":"客户类型"},{"name":"clientStTpCd","label":"客户状态"},{"name":"langTpCd","label":"通讯语言"},{"name":"premCountryTpCd","label":"常驻国家"},{"name":"residentTpCd","label":"居民类型"},{"name":"infoIntegFlag","label":"信息完整性标识"},{"name":"checkInd","label":"复核标识"},{"name":"offshoreInd","label":"离岸客户标识"},{"name":"finId","label":"金融机构标志"},{"name":"orgTpCd","label":"企业类型"},{"name":"industryTpCd","label":"组织所属行业"},{"name":"economicTpCd","label":"企业经济性质"},{"name":"ownershipTpCd","label":"企业出资人经济成分"},{"name":"rgstCountryTpCd","label":"注册国家"},{"name":"rgstZoneTpCd","label":"注册地区"},{"name":"listedTpCd","label":"上市类型"},{"name":"spdbScaleTpCd","label":"企业规模（行内）"},{"name":"miitScaleTpCd","label":"企业规模（工信部）"},{"name":"spclEconomicTpCd","label":"特殊经济区代码"},{"name":"adminZoneTpCd","label":"行政区代码"},{"name":"loanValidInd","label":"贷款卡有效标识"},{"name":"businessStTpCd","label":"经营状态"},{"name":"regionTpCd","label":"所属地区"},{"name":"economicRegionTpCd","label":"客户所属经济区域"},{"name":"developEmpNo","label":"开拓人（员工编号）"},{"name":"establishedDt","label":"成立日期"},{"name":"registerDt","label":"注册登记日期"},{"name":"spvisorDepartment","label":"上级主管部门"},{"name":"loanCardNo","label":"贷款卡号"},{"name":"businessScope","label":"经营范围"},{"name":"staffNum","label":"员工人数"},{"name":"loyalScore","label":"忠诚度得分"},{"name":"basicAcctBank","label":"基本账户行"},{"name":"historyName","label":"历史名称"},{"name":"defaultPb","label":"客户违约概率"},{"name":"lastUpdateTms","label":"最后更新时间"}]);
$.data(labelCache,"addFinancialOrg",[{"name":"clientCode","label":"企业客户类型"},{"name":"idNum","label":"证件号码*"},{"name":"expiryDt","label":"证件有效期*"},{"name":"establishedDt","label":"成立日期*"},{"name":"clientName","label":"客户名称*"},{"name":"idNum01","label":"法人证件号码*"},{"name":"chineseName01","label":"法人中文名*"},{"name":"chineseName02","label":"财务联系人中文名*"},{"name":"idNum02","label":"财务联系人证件号码*"},{"name":"mobile01","label":"法人手机号码*"},{"name":"mobile02","label":"财务联系人手机号码*"},{"name":"developEmpNo","label":"开拓人(员工编号)"},{"name":"registerDt","label":"注册登记日期*"},{"name":"postCode","label":"邮政编码"},{"name":"address","label":"具体地址*"},{"name":"ctcmthNum","label":"联系信息*"},{"name":"spvisorDepartment","label":"上级主管部门"},{"name":"loanCardNo","label":"贷款卡号"},{"name":"businessScope","label":"经营范围"},{"name":"staffNum","label":"员工人数"},{"name":"loyalScore","label":"忠诚度得分"},{"name":"defaultPb","label":"违约概率"},{"name":"taxregAcctNo","label":"税务登记银行账号"},{"name":"taxregAcctBankName","label":"税务登记银行"},{"name":"balanceTpCd","label":"资产负债类型"},{"name":"registerAmt","label":"注册资金*"},{"name":"idTpCd","label":"证件类型*"},{"name":"clientStTpCd","label":"客户分类"},{"name":"clientStTpCd","label":"客户状态"},{"name":"relTpCd01","label":"关联人类型"},{"name":"idTpCd01","label":"法人证件类型*"},{"name":"relTpCd02","label":"关联人类型"},{"name":"idTpCd02","label":"财务联系人证件类型*"},{"name":"langTpCd","label":"通讯语言"},{"name":"premCountryTpCd","label":"常驻国家"},{"name":"residentTpCd","label":"居民类型"},{"name":"offshoreInd","label":"离岸客户标识"},{"name":"orgTpCd","label":"企业类型*"},{"name":"industryTpCd","label":"行业类型*"},{"name":"economicTpCd","label":"经济类型*"},{"name":"rgstCountryTpCd","label":"注册国家*"},{"name":"rgstZoneTpCd","label":"注册地区*"},{"name":"ownershipTpCd","label":"企业性质*"},{"name":"listedTpCd","label":"上市类型"},{"name":"miitScaleTpCd","label":"企业规模*"},{"name":"adrUsageTpCd","label":"地址类型"},{"name":"regionTpCd","label":"所属地区"},{"name":"economicRegionTpCd","label":"所属经济区域"},{"name":"ctcmthTpCd","label":"联系类型*"},{"name":"spclEconomicTpCd","label":"特殊经济区代码"},{"name":"loanValidInd","label":"贷款卡有效标识"},{"name":"businessStTpCd","label":"经营状态"},{"name":"taxpayerTpCd","label":"纳税人类型"},{"name":"currencyTpCd","label":"货币类型*"}]);
$.data(labelCache,"updateFinancialOrg",[{"name":"developEmpNo","label":"开拓人（员工编号）"},{"name":"establishedDt","label":"成立日期"},{"name":"registerDt","label":"注册登记日期"},{"name":"spvisorDepartment","label":"上级主管部门"},{"name":"loanCardNo","label":"贷款卡号"},{"name":"businessScope","label":"经营范围"},{"name":"staffNum","label":"员工人数"},{"name":"loyalScore","label":"忠诚度得分"},{"name":"basicAcctBank","label":"基本账户行"},{"name":"historyName","label":"历史名称"},{"name":"defaultPb","label":"客户违约概率"},{"name":"lastUpdateTms","label":"最后更新时间"},{"name":"clientCode","label":"客户类型"},{"name":"clientStTpCd","label":"客户状态"},{"name":"langTpCd","label":"通讯语言"},{"name":"premCountryTpCd","label":"常驻国家"},{"name":"residentTpCd","label":"居民类型"},{"name":"infoIntegFlag","label":"信息完整性标识"},{"name":"checkInd","label":"复核标识"},{"name":"offshoreInd","label":"离岸客户标识"},{"name":"finId","label":"金融机构标志"},{"name":"orgTpCd","label":"企业类型"},{"name":"industryTpCd","label":"组织所属行业"},{"name":"economicTpCd","label":"企业经济性质"},{"name":"ownershipTpCd","label":"企业出资人经济成分"},{"name":"rgstCountryTpCd","label":"注册国家"},{"name":"rgstZoneTpCd","label":"注册地区"},{"name":"listedTpCd","label":"上市类型"},{"name":"spdbScaleTpCd","label":"企业规模（行内）"},{"name":"miitScaleTpCd","label":"企业规模（工信部）"},{"name":"spclEconomicTpCd","label":"特殊经济区代码"},{"name":"adminZoneTpCd","label":"行政区代码"},{"name":"loanValidInd","label":"贷款卡有效标识"},{"name":"businessStTpCd","label":"经营状态"},{"name":"regionTpCd","label":"所属地区"},{"name":"economicRegionTpCd","label":"客户所属经济区域"}]);
$.data(labelCache,"updatePersonFinance",[{"label":"货币类型","name":"currencyTpCd"},{"label":"资产负债类型","name":"balanceTpCd"},{"label":"金额","name":"balanceAmt"},{"label":"最后更新时间","name":"lastUpdateTms"}]);
$.data(labelCache,"addOrgClientRel",[{"label":"关系类型","name":"relTpCd"},{"label":"主体关系客户号","name":"fromClientId"},{"label":"从属关系客户号","name":"toClientId"},{"label":"最后更新时间","name":"lastUpdateTms"}]);
$.data(labelCache,"addOrgClientRel",[{"label":"关系类型","name":"relTpCd"},{"label":"主体关系客户号","name":"fromClientId"},{"label":"从属关系客户号","name":"toClientId"},{"label":"最后更新时间","name":"lastUpdateTms"}]);


