package com.dev.huining.soft.web.zfire.pojo.entity;

// Generated 2013-9-23 20:27:50 by Hibernate Tools 3.4.0.CR1

/**
 * SysDict generated by hbm2java
 */
public class SysDict implements java.io.Serializable {

//	private String id;
	private String sys;
	private String dictno;
	private String dkey;
	private String dvalue;
	private String remark;

	public SysDict() {
	}

	public String getSys() {
		return this.sys;
	}

	public void setSys(String sys) {
		this.sys = sys;
	}

	public String getDictno() {
		return this.dictno;
	}

	public void setDictno(String dictno) {
		this.dictno = dictno;
	}

	public String getDkey() {
		return this.dkey;
	}

	public void setDkey(String dkey) {
		this.dkey = dkey;
	}

	public String getDvalue() {
		return this.dvalue;
	}

	public void setDvalue(String dvalue) {
		this.dvalue = dvalue;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
