package com.dev.huining.soft.web.zfire.pojo.entity;

// Generated 2013-9-23 20:27:50 by Hibernate Tools 3.4.0.CR1

/**
 * SysLayoutType generated by hbm2java
 */
public class SysLayoutType implements java.io.Serializable {

	private String id;
	private String lid;
	private String location;
	private String remark;

	public SysLayoutType() {
	}

	public SysLayoutType(String id) {
		this.id = id;
	}

	public SysLayoutType(String id, String lid, String location, String remark) {
		this.id = id;
		this.lid = lid;
		this.location = location;
		this.remark = remark;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLid() {
		return this.lid;
	}

	public void setLid(String lid) {
		this.lid = lid;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
