package com.dev.huining.soft.web.zfire.pojo.entity;

// Generated 2013-9-23 20:27:50 by Hibernate Tools 3.4.0.CR1

/**
 * SysLayout generated by hbm2java
 */
public class SysLayout implements java.io.Serializable {

	private String id;
	private String lcode;
	private String module;
	private String remark;

	public SysLayout() {
	}

	public SysLayout(String id) {
		this.id = id;
	}

	public SysLayout(String id, String lcode, String module, String remark) {
		this.id = id;
		this.lcode = lcode;
		this.module = module;
		this.remark = remark;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLcode() {
		return this.lcode;
	}

	public void setLcode(String lcode) {
		this.lcode = lcode;
	}

	public String getModule() {
		return this.module;
	}

	public void setModule(String module) {
		this.module = module;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
