package com.dev.huining.soft.web.zfire.pojo.entity;

// Generated 2013-9-23 20:27:50 by Hibernate Tools 3.4.0.CR1

/**
 * SysLayoutCase generated by hbm2java
 */
public class SysLayoutCase implements java.io.Serializable {

	private String id;
	private String ltid;
	private String pageid;
	private String params;
	private Integer lorder;
	private String remark;

	public SysLayoutCase() {
	}

	public SysLayoutCase(String id) {
		this.id = id;
	}

	public SysLayoutCase(String id, String ltid, String pageid, String params,
			Integer lorder, String remark) {
		this.id = id;
		this.ltid = ltid;
		this.pageid = pageid;
		this.params = params;
		this.lorder = lorder;
		this.remark = remark;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getLtid() {
		return this.ltid;
	}

	public void setLtid(String ltid) {
		this.ltid = ltid;
	}

	public String getPageid() {
		return this.pageid;
	}

	public void setPageid(String pageid) {
		this.pageid = pageid;
	}

	public String getParams() {
		return this.params;
	}

	public void setParams(String params) {
		this.params = params;
	}

	public Integer getLorder() {
		return this.lorder;
	}

	public void setLorder(Integer lorder) {
		this.lorder = lorder;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
