package com.dev.huining.soft.web.zfire.pojo.entity;

// Generated 2013-9-23 20:27:50 by Hibernate Tools 3.4.0.CR1

/**
 * SysOrgz generated by hbm2java
 */
public class SysOrgz implements java.io.Serializable {

	private String id;
	private String oname;
	private String remark;
	private Character enable;
	private String porgzId;

	public SysOrgz() {
	}

	public SysOrgz(String id) {
		this.id = id;
	}

	public SysOrgz(String id, String oname, String remark, Character enable,
			String porgzId) {
		this.id = id;
		this.oname = oname;
		this.remark = remark;
		this.enable = enable;
		this.porgzId = porgzId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getOname() {
		return this.oname;
	}

	public void setOname(String oname) {
		this.oname = oname;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Character getEnable() {
		return this.enable;
	}

	public void setEnable(Character enable) {
		this.enable = enable;
	}

	public String getPorgzId() {
		return this.porgzId;
	}

	public void setPorgzId(String porgzId) {
		this.porgzId = porgzId;
	}

}
