package com.dev.huining.soft.web.zfire.pojo.entity;

// Generated 2013-9-23 20:27:50 by Hibernate Tools 3.4.0.CR1

/**
 * SysRoleright generated by hbm2java
 */
public class SysRoleright implements java.io.Serializable {

	private String id;
	private String rightcode;

	public SysRoleright() {
	}

	public SysRoleright(String id) {
		this.id = id;
	}

	public SysRoleright(String id, String rightcode) {
		this.id = id;
		this.rightcode = rightcode;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getRightcode() {
		return this.rightcode;
	}

	public void setRightcode(String rightcode) {
		this.rightcode = rightcode;
	}

}
