package com.dev.huining.soft.web.zfire.pojo.entity;

// Generated 2013-9-23 20:27:50 by Hibernate Tools 3.4.0.CR1

/**
 * SysSqlcfg generated by hbm2java
 */
public class SysSqlcfg implements java.io.Serializable {

	private String id;
	private String ucId;
	private Integer type;
	private String csql;
	private String remark;

	public SysSqlcfg() {
	}

	public SysSqlcfg(String id) {
		this.id = id;
	}

	public SysSqlcfg(String id, String ucId, Integer type, String csql,
			String remark) {
		this.id = id;
		this.ucId = ucId;
		this.type = type;
		this.csql = csql;
		this.remark = remark;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUcId() {
		return this.ucId;
	}

	public void setUcId(String ucId) {
		this.ucId = ucId;
	}

	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public String getCsql() {
		return this.csql;
	}

	public void setCsql(String csql) {
		this.csql = csql;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

}
