package com.dev.huining.soft.web.zfire.pojo.entity;

// Generated 2013-9-23 20:27:50 by Hibernate Tools 3.4.0.CR1

/**
 * SysUserRole generated by hbm2java
 */
public class SysUserRole implements java.io.Serializable {

	private String id;
	private String uid;
	private String rid;

	public SysUserRole() {
	}

	public SysUserRole(String id) {
		this.id = id;
	}

	public SysUserRole(String id, String uid, String rid) {
		this.id = id;
		this.uid = uid;
		this.rid = rid;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUid() {
		return this.uid;
	}

	public void setUid(String uid) {
		this.uid = uid;
	}

	public String getRid() {
		return this.rid;
	}

	public void setRid(String rid) {
		this.rid = rid;
	}

}
