package com.dev.huining.soft.web.zfire.pojo.entity;

// Generated 2013-9-23 20:27:50 by Hibernate Tools 3.4.0.CR1

/**
 * SysUccfg generated by hbm2java
 */
public class SysUccfg implements java.io.Serializable {

	private String id;
	private String ucode;
	private String ucName;
	private String beanId;
	private String method;
	private Integer iscache;

	public SysUccfg() {
	}

	public SysUccfg(String id) {
		this.id = id;
	}



	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUcode() {
		return this.ucode;
	}

	public void setUcode(String ucode) {
		this.ucode = ucode;
	}

	public String getUcName() {
		return this.ucName;
	}

	public void setUcName(String ucName) {
		this.ucName = ucName;
	}

	public String getBeanId() {
		return this.beanId;
	}

	public void setBeanId(String beanId) {
		this.beanId = beanId;
	}

	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	public Integer getIscache() {
		return this.iscache;
	}

	public void setIscache(Integer iscache) {
		this.iscache = iscache;
	}

}
