package com.dev.huining.soft.web.zfire.pojo.entity;

// Generated 2013-9-23 20:27:50 by Hibernate Tools 3.4.0.CR1

/**
 * SysViewcfg generated by hbm2java
 */
public class SysViewcfg implements java.io.Serializable {

	private String id;
	private String ucId;
	private String cvsId;
	private Integer level;
	private String title;
	private String dictNo;
	private Integer hrefType;
	private String href;
	private Integer dataType;
	private String formate;
	private Integer sort;
	private String align;
	private String minWidth;
	private String width;
	private String maxWidth;
	private String viewFlag;

	public SysViewcfg() {
	}

	public SysViewcfg(String id) {
		this.id = id;
	}

	public SysViewcfg(String id, String ucId, String cvsId, Integer level,
			String title, String dictNo, Integer hrefType, String href,
			Integer dataType, String formate, Integer sort, String align,
			String minWidth, String width, String maxWidth, String viewFlag) {
		this.id = id;
		this.ucId = ucId;
		this.cvsId = cvsId;
		this.level = level;
		this.title = title;
		this.dictNo = dictNo;
		this.hrefType = hrefType;
		this.href = href;
		this.dataType = dataType;
		this.formate = formate;
		this.sort = sort;
		this.align = align;
		this.minWidth = minWidth;
		this.width = width;
		this.maxWidth = maxWidth;
		this.viewFlag = viewFlag;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUcId() {
		return this.ucId;
	}

	public void setUcId(String ucId) {
		this.ucId = ucId;
	}

	public String getCvsId() {
		return this.cvsId;
	}

	public void setCvsId(String cvsId) {
		this.cvsId = cvsId;
	}

	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDictNo() {
		return this.dictNo;
	}

	public void setDictNo(String dictNo) {
		this.dictNo = dictNo;
	}

	public Integer getHrefType() {
		return this.hrefType;
	}

	public void setHrefType(Integer hrefType) {
		this.hrefType = hrefType;
	}

	public String getHref() {
		return this.href;
	}

	public void setHref(String href) {
		this.href = href;
	}

	public Integer getDataType() {
		return this.dataType;
	}

	public void setDataType(Integer dataType) {
		this.dataType = dataType;
	}

	public String getFormate() {
		return this.formate;
	}

	public void setFormate(String formate) {
		this.formate = formate;
	}

	public Integer getSort() {
		return this.sort;
	}

	public void setSort(Integer sort) {
		this.sort = sort;
	}

	public String getAlign() {
		return this.align;
	}

	public void setAlign(String align) {
		this.align = align;
	}

	public String getMinWidth() {
		return this.minWidth;
	}

	public void setMinWidth(String minWidth) {
		this.minWidth = minWidth;
	}

	public String getWidth() {
		return this.width;
	}

	public void setWidth(String width) {
		this.width = width;
	}

	public String getMaxWidth() {
		return this.maxWidth;
	}

	public void setMaxWidth(String maxWidth) {
		this.maxWidth = maxWidth;
	}

	public String getViewFlag() {
		return this.viewFlag;
	}

	public void setViewFlag(String viewFlag) {
		this.viewFlag = viewFlag;
	}

}
